AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
 Fan Out Pattern
Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FanOutFanIn
      Handler: PackageFanOutFanIn.FanIn::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:

  HelloWorldApi:
    Description: "FanIn Pattern"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "FanOutPattern"
    Value: !GetAtt FanInFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Fan Out function"
    Value: !GetAtt FanInRole.Arn
